# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ewd7qlbUcRSCev4vScu8j71Plq6t4_4j
"""


import streamlit as st
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import re

st.title("AI Resume Screening System")

@st.cache_resource
def load_model():
    return SentenceTransformer('all-MiniLM-L6-v2')

model = load_model()

uploaded_file = st.file_uploader("Upload Resume CSV", type=["csv"])
job_description = st.text_area("Enter Job Description")

if uploaded_file and job_description:
    df = pd.read_csv(uploaded_file)

    def clean_resume(text):
        text = re.sub('\s+', ' ', text)
        return text

    df['cleaned'] = df['resume_str'].apply(clean_resume)

    resume_embeddings = model.encode(df['cleaned'])
    job_embedding = model.encode([job_description])

    similarity = cosine_similarity(resume_embeddings, job_embedding)
    df['Score'] = similarity[0] # Changed to similarity[0] assuming job_embedding is a single row

    ranked = df.sort_values(by='Score', ascending=False)

    st.subheader("Top 5 Candidates")
    st.write(ranked[['category','Score']].head(5))
